# Generated by Django 4.2.4 on 2023-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogmodel_size_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='structure',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
