# Generated by Django 4.2.4 on 2023-09-09 13:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_catalogmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20),
        ),
    ]
