# Generated by Django 4.2.4 on 2023-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='structure',
            field=models.CharField(blank=True),
        ),
    ]
