# Generated by Django 4.2.4 on 2023-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifymodel',
            name='user',
        ),
        migrations.AddField(
            model_name='verifymodel',
            name='first_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifymodel',
            name='last_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifymodel',
            name='password',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifymodel',
            name='username',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
    ]
