# Generated by Django 4.2.4 on 2023-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_verifymodel_user_verifymodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifymodel',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
